export const words = {
  en: {
    title:'Quest · Standard Edition', good:'Good', evil:'Evil', success:'Success', fail:'Fail',
    loyal:'Loyal Servant of Arthur', morgan:'Morgan le Fay', scion:'Scion', minion:'Minion of Mordred', changeling:'Changeling',
    lobby:'Lobby', team:'Team selection', quest:'Secret quest cards', transition:'Choose next leader', inspect:'Amulet inspection', discussion:'Final discussion', final:'Good’s Last Chance', ended:'Game over', cancelled:'Cancelled',
    players:'Players', leader:'Leader', round:'Quest', sizeLabel:'Required team size', teamLabel:'Team', magicLabel:'Magic token', veterans:'Previous leaders', amulets:'Amulet holders', history:'Quest results', winner:'Winner', submittedLabel:'Submitted',
    lobbyHelp:'Use /quest join, then the host uses /quest start.', teamHelp:'The leader uses /quest team. There is no team vote.', questHelp:'Team members: /quest action to submit a secret card.', transitionHelp:'The outgoing leader uses /quest next. After quest 2 in a six-player game, also select an amulet holder.', inspectHelp:'The amulet holder uses /quest inspect. The result is private.', discussionHelp:'Discuss for five minutes. Then use /quest final to open secret accusations. Stop discussing after the deadline.', finalHelp:'Everyone: /quest action and choose two other players. All choices remain hidden until everyone submits.',
    roleLabel:'Your role', allies:'Known Evil players', noAllies:'You have no initial information about other players.', morganHelp:'You may play Success or Fail, even with the Magic token.', evilHelp:'You may play Success or Fail. With the Magic token, you must play Success.', loyalHelp:'You must always play Success.', inspections:'Your amulet results',
    saved:'Saved.', privatePrompt:'Choose your secret action. Submission is final.', accusation:'Choose exactly two other players', inspectResult:'Amulet result', deadline:'Discussion ends', reveal:'Roles', rulesTitle:'Standard rules · 4–6 players',
    rules:'Good wins after 3 successful quests. After 2 failed quests at 4 players, or 3 at 5–6, discuss for 5 minutes and enter Good’s Last Chance. Each player secretly chooses 2 other players; only Good choices count. Good must collectively identify every Evil player and no Good player. If every quest leader was Evil, Good wins instead.\nNo team voting. One Fail defeats any quest in these player counts. The leader assigns Magic to a team member: they must play Success, except Morgan le Fay. No player can lead twice.\n4: 2 Good / 2 Evil, teams 2-3-3-2 (board B: 2-3-2-3). 5: 3 Good / 2 Evil, teams 2-3-2-4-3. 6: 3 Good / 3 Evil, teams 2-3-4-3-4.\n4–5: Morgan knows Scion; Scion knows nobody. 6: Morgan and Minion know each other; Changeling is unknown to them and knows nobody.\n6 only: after quest 2, the outgoing leader assigns the next leader and a different amulet holder. Neither may be a prior leader or amulet holder. The holder privately checks another eligible player’s alignment, not role. Amulet holders cannot lead.',
    errors:{ size:'Only 4, 5 or 6 players are supported.', language:'Choose en or zh.', board:'Choose board A or B.', member:'You must be a player in this game.', phase:'That action is unavailable in this phase.', joined:'You have already joined.', full:'The lobby is full.', hostLeave:'The host must cancel the lobby to leave.', host:'Only the host can do this.', notFull:'The lobby must be full before starting.', notStarted:'The game has not started.', leader:'Only the current leader can do this.', teamSize:'Choose exactly the required number of different players.', magic:'Magic must be assigned to a team member.', teamMember:'You are not on this quest team.', submitted:'You have already submitted; choices cannot be changed.', card:'Invalid card.', forcedSuccess:'You must play Success.', eligibleLeader:'Choose a player who has never led or held an amulet.', eligibleAmulet:'Choose a different player who has never led or held an amulet.', noAmulet:'There is no amulet at this transition.', holder:'Only the amulet holder can inspect.', inspectTarget:'Choose a player who has never held an amulet or been inspected.', discussion:'The five-minute discussion has not ended.', targets:'Choose exactly two different players other than yourself.', exists:'This channel already has an active game.', missing:'No game here. Use /quest create.', stale:'This action belongs to an old game or round. Use /quest action again.', bot:'Bots cannot join.', permission:'Only the host or a server member with Manage Server can cancel.', internal:'The operation could not be completed. Use /quest status to check the saved state.', unsupported:'Use this command in a server text channel.' }
  },
  zh: {
    title:'阿瓦隆2号 · Quest 普通版', good:'好人', evil:'坏人', success:'成功', fail:'失败',
    loyal:'亚瑟忠臣', morgan:'摩根勒菲', scion:'继承者', minion:'莫德雷德爪牙', changeling:'换形者',
    lobby:'等待加入', team:'领袖组队', quest:'秘密提交任务牌', transition:'选择下一任领袖', inspect:'护符查验', discussion:'最终讨论', final:'好人的最后机会', ended:'游戏结束', cancelled:'已取消',
    players:'玩家', leader:'领袖', round:'任务', sizeLabel:'组队人数', teamLabel:'任务队伍', magicLabel:'魔法指示物', veterans:'当过领袖的玩家', amulets:'护符持有人', history:'任务记录', winner:'胜方', submittedLabel:'已提交',
    lobbyHelp:'使用 /quest join 加入，人数齐后房主使用 /quest start。', teamHelp:'领袖使用 /quest team 组队，无需全员投票。', questHelp:'任务队员使用 /quest action 秘密提交任务牌。', transitionHelp:'本轮领袖使用 /quest next。6 人局第 2 轮之后，同时指定护符持有人。', inspectHelp:'护符持有人使用 /quest inspect，结果仅本人可见。', discussionHelp:'讨论五分钟，到时使用 /quest final 开始秘密指认。截止后请停止讨论。', finalHelp:'所有玩家使用 /quest action，选择另外两人。全部提交前不公开任何指认。',
    roleLabel:'你的身份', allies:'你知道的坏人', noAllies:'你没有其他玩家的初始身份信息。', morganHelp:'可以出成功或失败，即使拿到魔法指示物。', evilHelp:'可以出成功或失败；拿到魔法指示物时必须成功。', loyalHelp:'你必须出成功。', inspections:'你的护符查验记录',
    saved:'已保存。', privatePrompt:'请选择秘密行动，提交后不能更改。', accusation:'选择另外两名不同玩家', inspectResult:'护符查验结果', deadline:'讨论截止时间', reveal:'身份揭晓', rulesTitle:'普通版规则 · 4 至 6 人',
    rules:'三次任务成功，好人获胜。4 人局两次失败，5、6 人局三次失败后，讨论五分钟，进入好人的最后机会。每人秘密指认另外两人，只计算好人的指认；必须合起来覆盖全部坏人且不能指到好人。若每一轮领袖都是坏人，好人获胜。\n无组队表决。这些人数下任何一张失败牌都会使任务失败。领袖给一名队员魔法，该玩家必须成功，摩根除外。每人最多当一次领袖。\n4 人：2 好 2 坏，任务人数 2-3-3-2（B 面 2-3-2-3）。5 人：3 好 2 坏，2-3-2-4-3。6 人：3 好 3 坏，2-3-4-3-4。\n4、5 人：摩根知道继承者，继承者不认识其他坏人。6 人：摩根和爪牙互认，换形者不认识他们，他们也不认识换形者。\n仅 6 人局：第 2 轮结束后，本轮领袖同时指定新领袖和不同的护符持有人，两者均不能当过领袖或持有护符。护符持有人秘密查验合资格玩家的阵营，不查具体角色；护符持有人不能当领袖。',
    errors:{ size:'只支持 4、5、6 人局。', language:'请选择 en 或 zh。', board:'请选择 A 或 B 面。', member:'你不是本局玩家。', phase:'当前阶段不能执行此操作。', joined:'你已经加入了。', full:'人数已满。', hostLeave:'房主需要取消房间才能退出。', host:'只有房主能执行此操作。', notFull:'人数齐后才能开始。', notStarted:'游戏尚未开始。', leader:'只有当前领袖能执行此操作。', teamSize:'请选择规定人数，且不能重复。', magic:'魔法必须给任务队员。', teamMember:'你不是本轮任务队员。', submitted:'你已经提交，不能更改。', card:'无效任务牌。', forcedSuccess:'你必须提交成功牌。', eligibleLeader:'新领袖不能当过领袖或持有护符。', eligibleAmulet:'护符持有人不能当过领袖或持有护符，且不能是新领袖。', noAmulet:'此时不能分配护符。', holder:'只有护符持有人能查验。', inspectTarget:'不能查验持有过护符或被护符查验过的玩家。', discussion:'五分钟讨论尚未结束。', targets:'请选择另外两名不同玩家。', exists:'这个频道已有进行中的游戏。', missing:'本频道没有游戏，使用 /quest create 创建。', stale:'此操作来自旧游戏或旧轮次，请重新使用 /quest action。', bot:'机器人不能加入游戏。', permission:'只有房主或拥有管理服务器权限的成员能取消。', internal:'操作未能完成，请使用 /quest status 查看已保存的状态。', unsupported:'请在服务器文字频道使用。' }
  }
};
export function dictionary(lang) { return words[lang]||words.en; }
export function language(locale) { return locale?.startsWith('zh')?'zh':'en'; }
export const mention = id => `<@${id}>`;
export function status(g) {
  const w=dictionary(g.language), lines=[`**${w.title}** — ${w[g.phase]}`,`${w.players}: ${g.players.map(mention).join(' ')} (${g.players.length}/${g.size})`];
  if(g.roles) {
    lines.push(`${w.round}: ${g.round+1}/${g.size===4?4:5}`,`${w.leader}: ${mention(g.leader)}`);
    if(g.phase==='team') lines.push(`${w.sizeLabel}: ${g.size===4&&g.board==='b'?[2,3,2,3][g.round]:({4:[2,3,3,2],5:[2,3,2,4,3],6:[2,3,4,3,4]})[g.size][g.round]}`);
    if(g.team.length) lines.push(`${w.teamLabel}: ${g.team.map(mention).join(' ')} · ${w.magicLabel}: ${mention(g.magic)}`);
    lines.push(`${w.veterans}: ${g.veterans.map(mention).join(' ')}`);
    if(g.amulets.length) lines.push(`${w.amulets}: ${g.amulets.map(mention).join(' ')}`);
    if(g.history.length) lines.push(`${w.history}:\n${g.history.map(r=>`${r.round}. ${r.success?'✅':'❌'} ${w.fail}: ${r.fails} · ${w.leader}: ${mention(r.leader)} · ${r.team.map(mention).join(' ')} · ${w.magicLabel}: ${mention(r.magic)}`).join('\n')}`);
    if(g.phase==='quest') lines.push(`${w.submittedLabel}: ${Object.keys(g.cards).length}/${g.team.length}`);
    if(g.phase==='final') lines.push(`${w.submittedLabel}: ${Object.keys(g.accusations).length}/${g.size}`);
    if(g.phase==='discussion') lines.push(`${w.deadline}: <t:${Math.floor(g.discussionEnds/1000)}:R>`);
    if(g.winner) lines.push(`**${w.winner}: ${w[g.winner]}**`,`${w.reveal}: ${g.players.map(p=>`${mention(p)} — ${w[g.roles[p]]}`).join('; ')}`);
  }
  if(w[g.phase+'Help']) lines.push(w[g.phase+'Help']);
  return lines.join('\n');
}
